import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F8F8",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 10,
    paddingTop: Platform.select({
      ios: 20,
      android: 20,
    }),
    backgroundColor: "#F8F8F8",
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333333",
  },
  headerRight: {
    width: 40,
  },
  content: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 40,
  },
  visualizationContainer: {
    marginBottom: 40,
  },
  recordingCircle: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "#E8F2FF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: "#2176FF",
  },
  recordingCircleActive: {
    backgroundColor: "#FF4444",
    borderColor: "#FF4444",
  },
  recordingCirclePlaying: {
    backgroundColor: "#4CAF50",
    borderColor: "#4CAF50",
  },
  timerContainer: {
    flexDirection: "row",
    alignItems: "baseline",
    marginBottom: 16,
  },
  timerText: {
    fontSize: 48,
    fontWeight: "bold",
    color: "#333333",
  },
  durationText: {
    fontSize: 24,
    color: "#A0A0A0",
    marginLeft: 8,
  },
  statusText: {
    fontSize: 16,
    color: "#666666",
    marginBottom: 40,
    textAlign: "center",
  },
  progressContainer: {
    width: "100%",
    alignItems: "center",
    marginBottom: 20,
  },
  progressBar: {
    width: "80%",
    height: 8,
    backgroundColor: "#E0E0E0",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#2176FF",
    borderRadius: 4,
  },
  uploadingIndicator: {
    marginTop: 16,
  },
  controlsContainer: {
    marginBottom: 40,
  },
  recordButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#2176FF",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#2176FF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  stopButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#FF4444",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#FF4444",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  recordedControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
  },
  secondaryButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FF4444",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  playButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#4CAF50",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#4CAF50",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  sendButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#2176FF",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#2176FF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  instructionsContainer: {
    paddingHorizontal: 20,
  },
  instructionText: {
    fontSize: 14,
    color: "#A0A0A0",
    textAlign: "center",
    lineHeight: 20,
  },
});
