import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F8F8",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 10,
    paddingTop: Platform.select({
      ios: 20,
      android: 20,
    }),
  },
  headerContainer: {
    backgroundColor: "#F8F8F8",
    paddingBottom: 16,
    width: "100%",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#111827",
    marginTop: 0,
  },
  notificationIconPlaceholder: {
    width: 24,
    height: 24,
    backgroundColor: "#E0E0E0",
    borderRadius: 12,
  },
  profileCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1F6FF2",
    marginHorizontal: 14,
    marginTop: 14,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 7,
  },
  profileImage: {
    width: 64,
    height: 64,
    borderRadius: 32,
    marginRight: 14,
    borderWidth: 2.5,
    borderColor: "#FFFFFF",
  },
  profileInfo: {
    flex: 1,
  },
  profileTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  profileName: {
    flex: 1,
    fontSize: 22,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  verifiedBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(16, 185, 129, 0.2)",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    gap: 4,
  },
  verifiedBadgeText: {
    fontSize: 11,
    color: "#FFFFFF",
    fontWeight: "600",
  },
  profileHandle: {
    marginTop: 2,
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.95)",
  },
  profileMetaText: {
    marginTop: 3,
    fontSize: 12,
    color: "rgba(255, 255, 255, 0.86)",
  },
  section: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 5,
    paddingVertical: 10,
  },
  profileSectionsContainer: {
    paddingHorizontal: 14,
    paddingBottom: 32,
  },
  sectionTitle: {
    marginTop: 9,
    marginBottom: 9,
    marginHorizontal: 2,
    fontSize: 13,
    color: "#4B5563",
    fontWeight: "700",
    letterSpacing: 0.95,
  },
  secondarySectionTitle: {
    marginTop: 20,
  },
  sectionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E6EAF0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    overflow: "hidden",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#EDF1F5",
  },
  menuItemLast: {
    borderBottomWidth: 0,
  },
  menuIconCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 13,
  },
  menuTextContent: {
    flex: 1,
    paddingRight: 10,
  },
  menuItemTitle: {
    fontSize: 17,
    color: "#111827",
    fontWeight: "700",
  },
  menuItemSubtitle: {
    marginTop: 3,
    fontSize: 13,
    color: "#64748B",
    lineHeight: 18,
  },
  arrowIcon: {
    marginLeft: 0,
  },
  chevronCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F3F4F6",
  },
  logoutChevronCircle: {
    backgroundColor: "#FEE2E2",
  },
  logoutCard: {
    marginTop: 18,
    borderColor: "#FECACA",
  },
  logoutRow: {
    borderBottomWidth: 0,
  },
  logoutIconCircle: {
    backgroundColor: "#FEE2E2",
  },
  logoutTitle: {
    fontSize: 18,
    color: "#EF4444",
    fontWeight: "700",
  },
  logoutSubtitle: {
    marginTop: 2,
    fontSize: 13,
    color: "#EF4444",
  },
  appVersionContainer: {
    marginTop: 22,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  appVersionText: {
    fontSize: 14,
    color: "#6B7280",
    fontWeight: "500",
    lineHeight: 21,
  },
  switch: {
    transform: [{ scaleX: 0.8 }, { scaleY: 0.8 }],
    marginLeft: "auto",
  },
  moreTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333333",
    marginTop: 30,
    marginHorizontal: 20,
  },
  flexFill: {
    flex: 1,
  },
  rightAligned: {
    flex: 1,
    alignItems: "flex-end",
    marginTop: 10,
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingBottom: 96,
  },
  avatarContainer: {
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: {
    color: "white",
    fontWeight: "bold",
  },
  tabContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginHorizontal: 20,
    marginTop: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  tabButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
    marginRight: 20,
  },
  activeTabButton: {
    borderBottomColor: "#2176FF",
  },
  tabButtonText: {
    fontSize: 16,
    color: "#A0A0A0", // Lighter for inactive
    fontWeight: "bold",
  },
  activeTabButtonText: {
    color: "#333333", // Darker for active
  },
  tabContent: {
    flex: 1,
    marginTop: 10,
  },
  membershipCard: {
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 5,
    paddingTop: 10,
    paddingRight: 20,
    paddingBottom: 10,
    paddingLeft: 20,
    height: 200,
    backgroundColor: "#ffffff",
  },
  marginTop20: {
    marginTop: 20,
  },
});
