import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: Platform.select({
      ios: 20,
      android: 20,
    }),
    paddingBottom: 10,
    backgroundColor: "#FFFFFF",
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333333",
    flex: 1,
    textAlign: "center",
  },
  headerRight: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  searchIcon: {
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#333333",
    fontFamily: "Poppins-Regular",
  },
  filterContainer: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  filterButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: "#F5F5F5",
    alignItems: "center",
  },
  filterButtonWomenActive: {
    backgroundColor: "#FF007F",
  },
  filterButtonChildrenActive: {
    backgroundColor: "#8A2BE2",
  },
  filterButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333333",
  },
  filterButtonTextActive: {
    color: "#FFFFFF",
  },
  mapContainer: {
    marginBottom: 20,
  },
  mapBackground: {
    width: "100%",
    height: 400,
    backgroundColor: "#F5F5F5",
    borderRadius: 12,
    overflow: "hidden",
    position: "relative",
  },
  streetNameContainer: {
    position: "absolute",
    top: 20,
    left: 20,
    gap: 8,
  },
  streetName: {
    fontSize: 12,
    color: "#666666",
    fontFamily: "Poppins-Regular",
  },
  heatmapOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  heatmapBlur: {
    position: "absolute",
    borderRadius: 50,
    opacity: 0.6,
  },
  heatmapRed1: {
    width: 120,
    height: 120,
    backgroundColor: "#FF0000",
    top: 60,
    left: 40,
  },
  heatmapRed2: {
    width: 100,
    height: 100,
    backgroundColor: "#FF0000",
    top: 200,
    left: 180,
  },
  heatmapOrange: {
    width: 80,
    height: 80,
    backgroundColor: "#FF8C00",
    top: 280,
    left: 220,
  },
  heatmapYellow: {
    width: 90,
    height: 90,
    backgroundColor: "#FFD700",
    top: 120,
    left: 120,
  },
  heatmapGreen: {
    width: 70,
    height: 70,
    backgroundColor: "#00FF00",
    top: 300,
    left: 240,
  },
  mapControls: {
    position: "absolute",
    right: 12,
    top: 12,
    gap: 8,
  },
  mapControlButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  legendContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    marginTop: -40,
    marginHorizontal: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  legendTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333333",
    marginBottom: 12,
  },
  legendItems: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  legendGreen: {
    backgroundColor: "#00FF00",
  },
  legendYellow: {
    backgroundColor: "#FFD700",
  },
  legendOrange: {
    backgroundColor: "#FF8C00",
  },
  legendRed: {
    backgroundColor: "#FF0000",
  },
  legendText: {
    fontSize: 14,
    color: "#333333",
  },
  footerInstruction: {
    fontSize: 14,
    color: "#A0A0A0",
    textAlign: "center",
    marginTop: 20,
  },
});
